### PR TITLE
NRFE-3714: add optional scoping of extension

### PR DESCRIPTION
**Pull request by powli**
Use https://github.com/humbug/php-scoper to automatically scope the extension's dependencies - works best if the extensions provide the `scoper.inc.php` file themselves.

### CODE REVIEW

**Comment by shyim** [comment]
Did you tested that is still working as packed as phar?

**Comment by powli** [comment]
I have not. Might check that later today

**Comment by powli** [comment]
It does not. Maybe if we expect to have php-scoper installed globally? It is an optional feature... If php-scoper can not be found we could just skip the execution.

**Comment by shyim** [comment]
Hey,
can you fix the failing tests?

**Comment by powli** [comment]
@shyim fixed the tests and made it so that it is expected for php-scoper to be installed globally with graceful failure

**Review by shyim — APPROVED** [review]

**Pull request merged**
