### PR TITLE
Allow h2-h6 version titles multi-indented changelogs

### PR DESCRIPTION
**Pull request by JoshuaBehrens**

### CODE REVIEW

**Comment by shyim** [comment]
That code 1:1 copied from Platform. We would have with your change an incompatible changelog 🤔

**Comment by JoshuaBehrens** [comment]
What do you mean that it is an incompatible changelog?

**Comment by JoshuaBehrens** [comment]
https://github.com/shopware/platform/pull/947 I see what mean

**Comment by shyim** [comment]
The core PR got declined. I don't know we want this here

**Comment by JoshuaBehrens** [comment]
I am aware of the decline but I have an objection there. I am aware of the connection of these two :)

**Comment by shyim** [comment]
Please open the PR again, when it's merged in the Core :)

**Pull request closed without merging**
